"""
@file: log_lexicon/__init__.py
@description: Инициализация модуля лог-лексиконов
@created: 2025-10-03
@updated: 2025-10-07
"""

from app.lexicon.gettext import get_log_text

from .en import LOG_LEXICON_EN
from .main import (
    BOT_AI_MANAGER_CLOSE_TIMEOUT,
    BOT_AI_MANAGER_CLOSED,
    BOT_COMMANDS_SET,
    BOT_CRITICAL_ERROR,
    BOT_DB_CLOSE_TIMEOUT,
    BOT_DB_CLOSED,
    BOT_DB_INITIALIZING,
    BOT_INITIALIZED,
    BOT_KEYBOARD_INTERRUPT,
    BOT_POLLING_STARTED,
    BOT_POLLING_STOP_TIMEOUT,
    BOT_POLLING_STOPPED,
    BOT_PROGRAM_FINISHED,
    BOT_REGISTERED_ROUTERS,
    BOT_SESSION_CLOSE_TIMEOUT,
    BOT_SESSION_CLOSED,
    BOT_SHUTDOWN_COMPLETED,
    BOT_SHUTDOWN_ERROR,
    BOT_SHUTDOWN_STARTED,
    BOT_SIGNAL_RECEIVED,
    BOT_STARTED,
    BOT_STARTING,
    BOT_USER_INTERRUPTED,
    BOT_WEBHOOK_SET,
    BOT_WEBHOOK_STARTED,
)
from .ru import LOG_LEXICON_RU

# Для обратной совместимости по умолчанию используем русский лог-лексикон
LOG_LEXICON = LOG_LEXICON_RU

# Явно экспортируем модули
__all__ = [
    "BOT_AI_MANAGER_CLOSED",
    "BOT_AI_MANAGER_CLOSE_TIMEOUT",
    "BOT_COMMANDS_SET",
    "BOT_CRITICAL_ERROR",
    "BOT_DB_CLOSED",
    "BOT_DB_CLOSE_TIMEOUT",
    "BOT_DB_INITIALIZING",
    "BOT_INITIALIZED",
    "BOT_KEYBOARD_INTERRUPT",
    "BOT_POLLING_STARTED",
    "BOT_POLLING_STOPPED",
    "BOT_POLLING_STOP_TIMEOUT",
    "BOT_PROGRAM_FINISHED",
    "BOT_REGISTERED_ROUTERS",
    "BOT_SESSION_CLOSED",
    "BOT_SESSION_CLOSE_TIMEOUT",
    "BOT_SHUTDOWN_COMPLETED",
    "BOT_SHUTDOWN_ERROR",
    "BOT_SHUTDOWN_STARTED",
    "BOT_SIGNAL_RECEIVED",
    "BOT_STARTED",
    "BOT_STARTING",
    "BOT_USER_INTERRUPTED",
    "BOT_WEBHOOK_SET",
    "BOT_WEBHOOK_STARTED",
    "LOG_LEXICON",
    "LOG_LEXICON_EN",
    "LOG_LEXICON_RU",
    "get_log_text",
]
