"""Add user statistics and relationships for Stage 1.2

Revision ID: 202511222255
Revises: 202511222250
Create Date: 2025-11-22 22:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "202511222255"
down_revision: Union[str, None] = "202511222250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to users table
    op.add_column('users', sa.Column('total_chats', sa.Integer(), nullable=False, server_default='0', comment='Общее количество чатов'))
    op.add_column('users', sa.Column('total_messages_sent', sa.Integer(), nullable=False, server_default='0', comment='Общее количество отправленных сообщений'))
    op.add_column('users', sa.Column('favorite_character_id', sa.Integer(), nullable=True, comment='ID любимого персонажа'))
    
    # Create foreign key constraint for favorite_character_id
    op.create_foreign_key('fk_users_favorite_character_id', 'users', 'characters', ['favorite_character_id'], ['id'])
    
    # Create indexes
    op.create_index('idx_users_favorite_character', 'users', ['favorite_character_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_users_favorite_character', table_name='users')
    
    # Drop foreign key constraint
    op.drop_constraint('fk_users_favorite_character_id', 'users', type_='foreignkey')
    
    # Drop columns
    op.drop_column('users', 'favorite_character_id')
    op.drop_column('users', 'total_messages_sent')
    op.drop_column('users', 'total_chats')
    
    # ### end Alembic commands ###