"""Add characters, scenarios, chats and related tables for Stage 1.2

Revision ID: 202511222250
Revises: 82d758b7d903
Create Date: 2025-11-22 22:50:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202511222250"
down_revision: Union[str, None] = "82d758b7d903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create characters table
    op.create_table(
        "characters",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ID персонажа",
        ),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Имя персонажа"
        ),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="character_gender"),
            nullable=False,
            comment="Пол персонажа",
        ),
        sa.Column("age", sa.Integer(), nullable=False, comment="Возраст персонажа"),
        sa.Column(
            "description", sa.Text(), nullable=False, comment="Характер персонажа"
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=500),
            nullable=True,
            comment="URL аватара персонажа",
        ),
        sa.Column("system_prompt", sa.Text(), nullable=False, comment="Промпт для ИИ"),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли персонаж"
        ),
        sa.Column(
            "is_public", sa.Boolean(), nullable=False, comment="Публичный ли персонаж"
        ),
        sa.Column(
            "created_by_user_id",
            sa.BigInteger(),
            nullable=True,
            comment="ID пользователя-создателя",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата последнего обновления",
        ),
        sa.Column(
            "total_chats",
            sa.Integer(),
            nullable=False,
            comment="Общее количество чатов",
        ),
        sa.Column(
            "total_messages",
            sa.Integer(),
            nullable=False,
            comment="Общее количество сообщений",
        ),
        sa.Column(
            "rating_sum", sa.Integer(), nullable=False, comment="Сумма рейтингов"
        ),
        sa.Column(
            "rating_count", sa.Integer(), nullable=False, comment="Количество оценок"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_character_created_by", "characters", ["created_by_user_id"], unique=False
    )
    op.create_index(
        "idx_character_name_active", "characters", ["name", "is_active"], unique=False
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)

    # Create scenarios table
    op.create_table(
        "scenarios",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ID сценария",
        ),
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="Название сценария"
        ),
        sa.Column(
            "description", sa.Text(), nullable=False, comment="Описание сценария"
        ),
        sa.Column(
            "initial_prompt",
            sa.Text(),
            nullable=False,
            comment="Стартовый промпт сценария",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли сценарий"
        ),
        sa.Column(
            "is_public", sa.Boolean(), nullable=False, comment="Публичный ли сценарий"
        ),
        sa.Column(
            "min_age_rating",
            sa.Integer(),
            nullable=False,
            comment="Минимальный возрастной рейтинг",
        ),
        sa.Column(
            "created_by_user_id",
            sa.BigInteger(),
            nullable=True,
            comment="ID пользователя-создателя",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата последнего обновления",
        ),
        sa.Column(
            "total_chats",
            sa.Integer(),
            nullable=False,
            comment="Общее количество чатов",
        ),
        sa.Column(
            "total_messages",
            sa.Integer(),
            nullable=False,
            comment="Общее количество сообщений",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_scenario_created_by", "scenarios", ["created_by_user_id"], unique=False
    )
    op.create_index(
        "idx_scenario_title_active", "scenarios", ["title", "is_active"], unique=False
    )
    op.create_index(op.f("ix_scenarios_id"), "scenarios", ["id"], unique=False)
    op.create_index(op.f("ix_scenarios_title"), "scenarios", ["title"], unique=False)

    # Create chats table
    op.create_table(
        "chats",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ID чата",
        ),
        sa.Column(
            "user_id", sa.BigInteger(), nullable=False, comment="ID пользователя"
        ),
        sa.Column("character_id", sa.Integer(), nullable=False, comment="ID персонажа"),
        sa.Column("scenario_id", sa.Integer(), nullable=True, comment="ID сценария"),
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=True,
            comment="Пользовательское название",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли чат"),
        sa.Column(
            "memory_retention_days",
            sa.Integer(),
            nullable=True,
            comment="Дней хранения памяти (null = безлимит)",
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время последнего сообщения",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата последнего обновления",
        ),
        sa.Column(
            "total_messages",
            sa.Integer(),
            nullable=False,
            comment="Общее количество сообщений",
        ),
        sa.Column(
            "user_messages_count",
            sa.Integer(),
            nullable=False,
            comment="Количество сообщений пользователя",
        ),
        sa.Column(
            "ai_messages_count",
            sa.Integer(),
            nullable=False,
            comment="Количество сообщений ИИ",
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chat_created_at", "chats", ["created_at"], unique=False)
    op.create_index("idx_last_message", "chats", ["last_message_at"], unique=False)
    op.create_index(
        "idx_user_active_chats", "chats", ["user_id", "is_active"], unique=False
    )
    op.create_index(
        "idx_user_character_scenario",
        "chats",
        ["user_id", "character_id", "scenario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chats_character_id"), "chats", ["character_id"], unique=False
    )
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    op.create_index(
        op.f("ix_chats_scenario_id"), "chats", ["scenario_id"], unique=False
    )
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)

    # Create chat_messages table
    op.create_table(
        "chat_messages",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ID сообщения",
        ),
        sa.Column("chat_id", sa.Integer(), nullable=False, comment="ID чата"),
        sa.Column(
            "message_type",
            sa.Enum("user", "ai", "system", name="message_type"),
            nullable=False,
            comment="Тип сообщения",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="Содержимое сообщения"),
        sa.Column(
            "extra_data",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Дополнительные данные",
        ),
        sa.Column("ai_model", sa.String(length=50), nullable=True, comment="Модель ИИ"),
        sa.Column(
            "generation_time_ms",
            sa.Integer(),
            nullable=True,
            comment="Время генерации в миллисекундах",
        ),
        sa.Column(
            "token_count", sa.Integer(), nullable=True, comment="Количество токенов"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="Удалено ли сообщение"
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_created", "chat_messages", ["chat_id", "created_at"], unique=False
    )
    op.create_index(
        "idx_chat_type_created",
        "chat_messages",
        ["chat_id", "message_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_message_created_at", "chat_messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_chat_id"), "chat_messages", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_created_at"),
        "chat_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_message_type"),
        "chat_messages",
        ["message_type"],
        unique=False,
    )

    # Create character_tags table
    op.create_table(
        "character_tags",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ID тега",
        ),
        sa.Column("character_id", sa.Integer(), nullable=False, comment="ID персонажа"),
        sa.Column(
            "tag_name", sa.String(length=50), nullable=False, comment="Название тега"
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "tag_name", name="uq_character_tag"),
    )
    op.create_index(
        "idx_character_tag", "character_tags", ["character_id"], unique=False
    )
    op.create_index("idx_tag_name", "character_tags", ["tag_name"], unique=False)

    # Create character_ratings table
    op.create_table(
        "character_ratings",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ID рейтинга",
        ),
        sa.Column("character_id", sa.Integer(), nullable=False, comment="ID персонажа"),
        sa.Column(
            "user_id", sa.BigInteger(), nullable=False, comment="ID пользователя"
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
            comment="Рейтинг (1 = дизлайк, 5 = лайк)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата создания",
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "user_id", name="uq_character_user_rating"),
    )
    op.create_check_constraint(
        "check_rating_range", "character_ratings", "rating >= 1 AND rating <= 5"
    )
    op.create_index(
        "idx_character_rating", "character_ratings", ["character_id"], unique=False
    )
    op.create_index("idx_user_rating", "character_ratings", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop character_ratings table
    op.drop_index("idx_user_rating", table_name="character_ratings")
    op.drop_index("idx_character_rating", table_name="character_ratings")
    op.drop_table("character_ratings")

    # Drop character_tags table
    op.drop_index("idx_tag_name", table_name="character_tags")
    op.drop_index("idx_character_tag", table_name="character_tags")
    op.drop_table("character_tags")

    # Drop chat_messages table
    op.drop_index(op.f("ix_chat_messages_message_type"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_chat_id"), table_name="chat_messages")
    op.drop_index("idx_message_created_at", table_name="chat_messages")
    op.drop_index("idx_chat_type_created", table_name="chat_messages")
    op.drop_index("idx_chat_created", table_name="chat_messages")
    op.drop_table("chat_messages")

    # Drop chats table
    op.drop_index(op.f("ix_chats_user_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_scenario_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_character_id"), table_name="chats")
    op.drop_index("idx_user_character_scenario", table_name="chats")
    op.drop_index("idx_user_active_chats", table_name="chats")
    op.drop_index("idx_last_message", table_name="chats")
    op.drop_index("idx_chat_created_at", table_name="chats")
    op.drop_table("chats")

    # Drop scenarios table
    op.drop_index(op.f("ix_scenarios_title"), table_name="scenarios")
    op.drop_index(op.f("ix_scenarios_id"), table_name="scenarios")
    op.drop_index("idx_scenario_title_active", table_name="scenarios")
    op.drop_index("idx_scenario_created_by", table_name="scenarios")
    op.drop_table("scenarios")

    # Drop characters table
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_index("idx_character_name_active", table_name="characters")
    op.drop_index("idx_character_created_by", table_name="characters")
    op.drop_table("characters")

    # Drop enums
    op.execute("DROP TYPE IF EXISTS character_gender")
    op.execute("DROP TYPE IF EXISTS message_type")

    # ### end Alembic commands ###
