"""Add subscription and usage tables for Stage 1.3

Revision ID: 202511222300
Revises: 
Create Date: 2025-11-22 23:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202511222300"
down_revision: Union[str, None] = "202511222255"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create subscriptions table
    op.create_table(
        "subscriptions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Уникальный ID подписки",
        ),
        sa.Column(
            "user_id", sa.BigInteger(), nullable=False, comment="ID пользователя"
        ),
        sa.Column(
            "tier",
            sa.Enum(
                "FREE",
                "STANDARD",
                "PREMIUM",
                "DELUXE",
                "ADMIN",
                name="subscriptiontier",
            ),
            nullable=False,
            comment="Уровень подписки",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "EXPIRED", "CANCELLED", "PENDING", name="subscriptionstatus"
            ),
            nullable=False,
            comment="Статус подписки",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата начала подписки",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата окончания подписки",
        ),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата отмены подписки",
        ),
        sa.Column(
            "daily_message_limit",
            sa.Integer(),
            nullable=False,
            comment="Дневной лимит сообщений",
        ),
        sa.Column(
            "daily_image_limit",
            sa.Integer(),
            nullable=False,
            comment="Дневной лимит изображений",
        ),
        sa.Column(
            "memory_retention_days",
            sa.Integer(),
            nullable=True,
            comment="Дней хранения памяти (null = безлимит)",
        ),
        sa.Column(
            "has_image_generation",
            sa.Boolean(),
            nullable=False,
            comment="Есть ли возможность генерации изображений",
        ),
        sa.Column(
            "has_priority_queue",
            sa.Boolean(),
            nullable=False,
            comment="Есть ли приоритет в очереди",
        ),
        sa.Column("has_no_ads", sa.Boolean(), nullable=False, comment="Нет ли рекламы"),
        sa.Column(
            "max_characters_creation",
            sa.Integer(),
            nullable=True,
            comment="Максимум созданных персонажей (null = безлимит)",
        ),
        sa.Column(
            "max_scenarios_per_character",
            sa.Integer(),
            nullable=True,
            comment="Максимум сценариев на персонажа (null = безлимит)",
        ),
        sa.Column(
            "payment_provider",
            sa.String(length=50),
            nullable=True,
            comment="Провайдер платежа",
        ),
        sa.Column(
            "external_subscription_id",
            sa.String(length=200),
            nullable=True,
            comment="Внешний ID подписки",
        ),
        sa.Column(
            "last_payment_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата последнего платежа",
        ),
        sa.Column(
            "next_billing_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата следующего платежа",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="Дата последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_subscription_expires_at", "subscriptions", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_subscription_status", "subscriptions", ["status"], unique=False
    )
    op.create_index("idx_subscription_tier", "subscriptions", ["tier"], unique=False)
    op.create_index("idx_subscription_user_id", "subscriptions", ["user_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)

    # Create subscription_usage table
    op.create_table(
        "subscription_usage",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Уникальный ID записи использования",
        ),
        sa.Column(
            "subscription_id", sa.Integer(), nullable=False, comment="ID подписки"
        ),
        sa.Column(
            "usage_date", sa.Date(), nullable=False, comment="Дата использования"
        ),
        sa.Column(
            "messages_sent",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Отправлено сообщений",
        ),
        sa.Column(
            "images_generated",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Сгенерировано изображений",
        ),
        sa.Column(
            "characters_created",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Создано персонажей",
        ),
        sa.Column(
            "scenarios_created",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Создано сценариев",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            comment="Дата последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subscription_id", "usage_date", name="uq_subscription_daily_usage"
        ),
    )
    op.create_index(
        "idx_subscription_usage",
        "subscription_usage",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "idx_usage_date", "subscription_usage", ["usage_date"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_usage_id"), "subscription_usage", ["id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop subscription_usage table
    op.drop_index(op.f("ix_subscription_usage_id"), table_name="subscription_usage")
    op.drop_index("idx_usage_date", table_name="subscription_usage")
    op.drop_index("idx_subscription_usage", table_name="subscription_usage")
    op.drop_table("subscription_usage")

    # Drop subscriptions table
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_index("idx_subscription_user_id", table_name="subscriptions")
    op.drop_index("idx_subscription_tier", table_name="subscriptions")
    op.drop_index("idx_subscription_status", table_name="subscriptions")
    op.drop_index("idx_subscription_expires_at", table_name="subscriptions")
    op.drop_table("subscriptions")

    # Drop enums
    op.execute("DROP TYPE IF EXISTS subscriptiontier")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")

    # ### end Alembic commands ###
