"""Add payments table

Revision ID: add_payments_table
Revises: 82d758b7d903
Create Date: 2025-10-10

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_payments_table"
down_revision = "82d758b7d903"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="Внутренний ID платежа",
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=False,
            comment="ID пользователя в системе",
        ),
        sa.Column(
            "amount",
            sa.Integer(),
            nullable=False,
            comment="Сумма платежа в Telegram Stars",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=True,
            comment="Валюта платежа (XTR для Telegram Stars)",
        ),
        sa.Column(
            "payment_provider",
            sa.String(length=50),
            nullable=False,
            comment="Провайдер платежа (telegram_stars)",
        ),
        sa.Column(
            "payment_id",
            sa.String(length=255),
            nullable=False,
            comment="ID платежа от Telegram",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=True,
            comment="Статус платежа (completed, refunded, failed)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index("idx_payments_created_at", "payments", ["created_at"], unique=False)
    op.create_index("idx_payments_status", "payments", ["status"], unique=False)
    op.create_index("idx_payments_user_id", "payments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_payments_user_id", table_name="payments")
    op.drop_index("idx_payments_status", table_name="payments")
    op.drop_index("idx_payments_created_at", table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
